# Generated by Django 5.1.3 on 2024-11-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_predictiondata_delete_preditiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.IntegerField()),
                ('category_name', models.CharField()),
                ('is_positive', models.IntegerField()),
                ('image_metadata', models.CharField()),
                ('image_description', models.CharField()),
            ],
        ),
    ]
