# Generated by Django 5.1.3 on 2024-11-19 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_categorydate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryDate',
            new_name='CategoryData',
        ),
    ]
