# Generated by Django 5.1.3 on 2024-11-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_predictiondata_result_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadresponse',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
