# Generated by Django 5.1.3 on 2024-12-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_prediction_test_id_llmresponse_prediction_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmresponse',
            name='next_steps',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llmresponse',
            name='techniques',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
